# Generated by Django 5.0.14 on 2026-07-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('field_of_study', models.CharField(max_length=100)),
                ('grade', models.CharField(blank=True, help_text='e.g. GPA: 3.9/4.0 or First Class', max_length=50, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank if current study.', null=True)),
                ('description', models.TextField(blank=True, help_text='Honors, activities, or course highlights.')),
                ('order', models.IntegerField(default=0, help_text='Sort order.')),
            ],
            options={
                'verbose_name_plural': 'Education',
                'ordering': ['order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('description', models.TextField(help_text='Responsibilities and achievements. Use newlines for bullet points.')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank if current job.', null=True)),
                ('location', models.CharField(help_text='e.g. Remote, San Francisco, CA', max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Sort order (lower values first, or sorted by date).')),
            ],
            options={
                'ordering': ['order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(help_text='e.g. Senior Full Stack Engineer & Product Designer', max_length=100)),
                ('description', models.TextField(help_text='Short, catchy introduction used in the Hero section.')),
                ('biography', models.TextField(help_text='Detailed autobiography for the About page.')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('resume_pdf', models.FileField(blank=True, help_text='Upload your resume PDF.', null=True, upload_to='resume/')),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(help_text='e.g. San Francisco, CA', max_length=100)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('interests', models.TextField(blank=True, help_text='List your interests/hobbies, e.g. Design, Photography, Open Source')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(help_text='Brief project description for card view.')),
                ('content', models.TextField(blank=True, help_text='Detailed project breakdown (Markdown supported).')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('github_url', models.URLField(blank=True, null=True)),
                ('demo_url', models.URLField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('technologies', models.CharField(help_text='Comma-separated list of technologies, e.g. React, Django, Tailwind CSS', max_length=255)),
                ('order', models.IntegerField(default=0, help_text='Sort order for display (lower values first).')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Database', 'Database'), ('DevOps', 'DevOps'), ('Tools', 'Tools')], max_length=15)),
                ('order', models.IntegerField(default=0, help_text='Sort order for display.')),
            ],
            options={
                'ordering': ['category', 'order', 'name'],
            },
        ),
    ]
